---
- hosts: all
  become: true
  tasks:
  - name: Stop the running container
    shell: docker container stop $(docker container ls -aq)
    ignore_errors: yes

  - name: Remove the un-running containers
    shell: docker container rm $(docker container ls -aq)
    ignore_errors: yes

  - name: Remove docker images
    shell: docker rmi $(docker image ls -aq)
    ignore_errors: yes

  - name: Pull Docker images
    command: docker pull martin1051/myapp:latest
    
  - name: Run docker images to create Docker Containers
    command: docker run -d --name mycontainer -p 8080:8080 martin1051/myapp:latest
